on:
  schedule:
    - cron: '30 5 * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-20.04
    steps:
      - name: Not on Monday or Wednesday
        uses: jtalk/url-health-check-action@v3
        if: github.event.schedule != '30 5 * * 1,3'
        with:
          url: https://pokedex-4mm6.onrender.com/|https://pokeapi.co/api/v2/pokemon/?limit=50
          follow-redirect: false 
          max-attempts: 2
          retry-delay: 5s 
          retry-all: false